apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: qan
  name: qan-pv
  labels:
    app: qan-privnet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/qan"
