version: "3.8"

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qan

  backend:
    image: qanplatform/explorer-backend:v1-0-2-privnet
    restart: always
    environment:
      DB_HOST: db
  
  frontend:
    image: qanplatform/explorer-frontend:v1-0-1-privnet
    restart: always
    environment:
      BACKEND: backend:8000
    ports:
      - 80:80

  node:
    image: qanplatform/privnet:v1-0-4
    restart: always
    environment:
      BACKEND: backend:8000
